### ISSUE TITLE
Finding splat key issue

### ISSUE THREAD

**Issue by jwoertink** [luislavena/radix#12]
When you add a path with a splat, you're not able to find that without a trailing character

```crystal
[16:47PM] radix (master)$ icr -r ./src/radix
 => ok
icr(0.19.4) > tree = Radix::Tree(Symbol).new
 => #<Radix::Tree(Symbol):0x10a8c1f40 @root=#<Radix::Node(Symbol):0x10a8c3d40 @payload=nil, @priority=0, @key="", @placeholder=true, @children=[]>>
icr(0.19.4) > tree.add("/members*", :members)
 => #<Radix::Node(Symbol):0x106ddfd00 @payload=:members, @priority=0, @key="/members*", @placeholder=false, @children=[]>
icr(0.19.4) > tree.find("/members/1").found?
 => true
icr(0.19.4) > tree.find("/members/").found?
 => true
icr(0.19.4) > tree.find("/members").found? #<-- this is the one I want to find
 => false
icr(0.19.4) > tree.find("/members@@#$").found?
 => true
```

Maybe there can be something like an optional? `tree.add("/members(*)", :members)`

**Comment by luislavena** [comment]
Hello, thank you for your report.

The _catch all_ path is expected to be used in combination with the non-catch all path.

``` crystal
require "radix"

def print_result(result)
  if result.found?
    pp result.payload, result.params
  end
end

tree = Radix::Tree(Symbol).new
tree.add "/members", :members
tree.add "/members*trailing", :members_catch_all

print_result tree.find("/members")
print_result tree.find("/members/")
print_result tree.find("/members/1")
```

```
result.payload # => :members
result.params  # => {}
result.payload # => :members
result.params  # => {}
result.payload # => :members_catch_all
result.params  # => {"trailing" => "/1"}
```

Notice how trailing slashes are considered part of the first node and not the catch all one.

The catch all considers anything **that is not the trailing slash** to meet that condition. When no first node (or parent node if you build the tree) is defined, then there will be no matching element.

Since Radix is the extraction of our usage in another project, I'm failing to see why this could be considered a bug (since we never faced this scenario with our routes)

Can you provide me a real life example that same matching should fulfil both conditions?

Thank you.

**Comment by jwoertink** [comment]
Ah! I see. Ok, so this actually came about from a [new feature in Kemal](https://github.com/sdogruyol/kemal/blob/master/src/kemal/handler.cr#L31). I wanted a way to catch all the routes within a namespace, but it looks I can just do `only ["/members", "/members*"]` and that works. So it's more about the documentation than implementation here. 

I guess this really isn't a bug; however, an optional matching like what [sinatra](http://www.sinatrarb.com/intro.html#Routes) has would be nice (if it's not already doable).

``` ruby
get '/posts.?:format?' do
  # matches "GET /posts" and any extension "GET /posts.json", "GET /posts.xml" etc.
end
```

Otherwise, we can just close this out. :)

**Comment by luislavena** [comment]
Hello,

I wasn't aware of the changes in Kemal (I must confess I'm not a user) so will need to think a bit more if this can be considered a bug or not based on this usage or assumption.

Please bear with me a few days to think about it before we can close it.

Cheers!

PS: I haven't forgotten your other issue, have been a bit busy and is worth a proper response. :smile:

**Comment by jwoertink** [comment]
No worries! Thanks for the awesome shard 😄

**Comment by luislavena** [comment]
Hello @jwoertink, wanted to let you know that after some deliberation, we found to agree with your observation and we consider this a bug.

Given the following paths defined in the tree:

``` crystal
tree = Radix::Tree(Symbol).new
tree.add "/members", :members
tree.add "/members*trailing", :members_catch_all
```

Lookup for `/members` or `/members/` should always match `:members` node. However, if no specific route is defined, the catch all should pick up the definition:

``` crystal
tree = Radix::Tree(Symbol).new
tree.add "/members*trailing", :members_catch_all

# this should work
tree.find("/members").found? # => true
```

And right now that criteria does not work.

That will allow paths like `/members*format` where `format` param will be empty when lookup for `/members` is performed (example).

Will try to take a look at this during the weekend.

Thank you for your patience and your report!

Have a nice weekend.

**Comment by jwoertink** [comment]
Awesome! That's great news. 😁 Thanks for getting back. You have a great weekend too!
